version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend:
    build:
      context: ./backend
    container_name: backend-worker
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - rabbitmq
    command: sh -c "pnpm run dev & pnpm run worker"
